### PR TITLE
Initial Declaration of Tanvir's user with Cookie System

### LINKED ISSUE #58: Add my system
Once you have stabilized your infrastructure, I would like my system to be added there. I would really appreciate it.

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes: https://github.com/NiXium-org/NiXium/issues/58

CC @TanvirOnGH: Please review the code and address all `# TODO(Krey->Tanvir)` by using github's suggestions also please review the changes and brainstorm them or if you need additional changes then submit a merge request to my fork

Additionally please fork this repository in TanvirOnGH/nixos-config so that you can easily contribute while following the standard naming schema for nixos configs.

Also please set a wallpaper, note that because we are open-source it has to be under appropriate license

### CODE REVIEW

**Comment by TanvirOnGH** [comment]
I want full disk encryption (FDE) using custom LUKS Encryption (AES256XTS + Argon2id KDF)

**Comment by Kreyren** [comment]
@TanvirOnGH How much RAM capacity do you have or plan to have?

**Comment by TanvirOnGH** [comment]
> @TanvirOnGH How much RAM capacity do you have or plan to have?

24GB @3200Mhz atm. I've extra sticks so I switch 24<->32GB

**Comment by TanvirOnGH** [comment]
> @TanvirOnGH How much RAM capacity do you have or plan to have?

24GB 3200Mhz atm. I've extra sticks so I switch 24<->32GB

**Comment by Kreyren** [comment]
> 24GB 3200Mhz running on dual channel mode atm. I've extra sticks so I switch 24<->32GB. -- @TanvirOnGH (https://github.com/NiXium-org/NiXium/pull/84#issuecomment-2217264145)

Let's do 50GB swap then, usually i would do 32GB + 5 GB safety, but you seem to have a high workload that uses a lot of swap so lets do 50 to be safe.

**Comment by TanvirOnGH** [comment]
Do whatever you think is alright. Your configuration and way of doing things are really weird

**Comment by TanvirOnGH** [comment]
Your way of doings things are super weird so ig do whatever you think is alright

**Comment by ghost** [comment]
@Kreyren You may close this as I'm no longer interested.

**Comment by ghost** [comment]
@Kreyren You may re-open this. I'm interested again as I've free time now.

**Comment by Kreyren** [comment]
:thinking:

**Comment by Kreyren** [comment]
you are free to submit merge request for review to add your user and system

**Pull request closed without merging**
