### PR TITLE
Refactor: Hardened Discord for Kira, wireproxy, flatpak re-management, numlock on boot and User ID Management

### PR DESCRIPTION
**Pull request by Kreyren**
This merge request implements a hardened discord client which uses a user-deployed wireguard socks5 proxy that utilizes protonvpn + numlock enabled on boot + better management for flatpak + implemented declarative user ids instead of relying on the system to allocate them.

### CODE REVIEW

**Comment by Kreyren** [comment]
@TanvirOnGH Heads-up: Linux Xanmod 6.8.11(?) causes:
* disfunctional ethernet on tupac
* Broken USB on sinnenfreude

Consider avoiding this kernel version if you are using it

**Comment by Kreyren** [comment]
How do i always find these bugs in GitHub smh

**Comment by Kreyren** [comment]
OPEN!

**Comment by Kreyren** [comment]
:facepalm:

**Comment by ghost** [comment]
> Consider avoiding Linux Xanmod 6.8.11(?) kernel version if you are using it

Noted. I'm on:

image

**Pull request merged**
